# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

$MATCH_GIT_BASIC_AUTHORIZATION="d2FsaWRob3JjaGFuaTQ0QGdtYWlsLmNvbTpnaHBfRnZ4ODdzS1FXTzdYMEJhSm56ZjkxdHdrWjFnS1hrM2FvTFFC";
$GYM_CLEAN=true
default_platform(:ios)

platform :ios do

  desc "submit a new beta build to apple testflight"
  desc "this will also make sure the profile is up to date"
  lane :beta do
    increment_build_number  # increment locally build number
    match(type: "adhoc", git_basic_authorization: $MATCH_GIT_BASIC_AUTHORIZATION)
    #cocoapods(
    #  clean_install: true
    #) # to install dependencies with pod install
    gym(
      clean: $GYM_CLEAN,
      scheme: "videocall",
      workspace: './videocall.xcworkspace',
      include_bitcode: false,
    )
    pilot(
      #skip_waiting_for_build_processing: true  # pour ne pas attendre jusqu a la find u build ipa et passe au clean et commit 
    )
    clean_build_artifacts
    commit_version_bump(
      message: "Fastlane IOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip] ",
      xcodeproj: "./videocall.xcodeproj", # pcq fastalane va chercher et peut trouver plusieurs project, so on va definir le projet
      force: true
    )  # commit change do by action increment_build_number, use lane_context to access build number, "ci skip" to avoid ci loop trigered by commit

  end

  desc "test beta 2 with doc fastlane"
  lane :beta2 do
    sync_code_signing(
      type: "adhoc",
      git_basic_authorization: $MATCH_GIT_BASIC_AUTHORIZATION,
    )
    build_app(
      scheme: "videocall"
    )
    upload_to_testflight
    slack(
      message: "success beta ipa build"
    )
  end




  desc "screenshots generation and push to appstore"
  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end



  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
